# Generated by Django 4.0.1 on 2022-03-20 06:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField(default=datetime.time(10, 0))),
                ('departure_time', models.TimeField(default=datetime.time(10, 0))),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.TimeField(default=datetime.time(10, 0))),
                ('no_of_seats', models.IntegerField()),
                ('airline_name', models.CharField(max_length=100)),
                ('airport_location', models.CharField(max_length=100)),
                ('available_seats', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('class_type', models.CharField(max_length=100)),
                ('type_of_seat', models.CharField(choices=[('aisle', 'aisle'), ('window', 'window')], default='aisle', max_length=100)),
                ('seat_preference', models.CharField(choices=[('double', 'double'), ('triple', 'triple')], default='double', max_length=100)),
                ('is_special', models.BooleanField(default=False)),
                ('special_seat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=100)),
                ('depture_date', models.DateField(default=datetime.datetime.today)),
                ('fare', models.IntegerField()),
                ('passport', models.CharField(max_length=100)),
                ('government_id_type', models.CharField(choices=[('adhaar', 'adhaar'), ('driving_license', 'driving_license')], default='adhaar', max_length=100)),
                ('government_id_number', models.CharField(max_length=100)),
                ('health_status', models.CharField(max_length=100)),
                ('booking_date', models.DateField(default=datetime.datetime.today)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_pay', models.CharField(choices=[('upi', 'upi'), ('net_banking', 'net_banking'), ('bank_transfer', 'bank_transfer')], default='upi', max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticket')),
            ],
        ),
    ]
